# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: npm install
    
    - run: npm run build --if-present
    
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Deploy NodeJS App
      uses: appleboy/ssh-action@master
      env:
        NODEJS_DIR: /home/nodejs
        CLONE_DIR: twilio_apps
        DEPLOY_DIR: deployed
      with:
        host: twilio.awkwardweirdterribleandbad.com
        key: ${{ secrets.DIGITALOCEAN_PRIVATE_SSH_KEY}}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        envs: NODEJS_DIR, CLONE_DIR, DEPLOY_DIR
        script: |
          export -p
          set +e # Do not exit on error
          sudo -u nodejs pm2 delete hello
          set -e # Exit on error
          cd $NODEJS_DIR
          # Remove any previous clones
          rm -rf $NODEJS_DIR/$CLONE_DIR
          git clone https://github.com/rodmhgl/twilio_apps.git
          # This is needed for the way I handle precommit hooks
          mkdir -p $NODEJS_DIR/$DEPLOY_DIR/.git/hooks
          # Copy the updated repo to our deployment folder
          rsync -ac --delete --progress $NODEJS_DIR/$CLONE_DIR/ $NODEJS_DIR/$DEPLOY_DIR --exclude .git --quiet
          cd $NODEJS_DIR/$DEPLOY_DIR
          npm install
          sudo -u nodejs pm2 start ecosystem.config.js --watch
          sudo -u nodejs pm2 save
          # Cleanup after ourselves
          rm -rf $NODEJS_DIR/$CLONE_DIR
          exit
    - name: Update Twilio Webhook URLs
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        BAKER_SID: ${{ secrets.BAKER_SID}}
        FREEBIRD_SID: ${{ secrets.FREEBIRD_SID}}
        GETITON_SID: ${{ secrets.GETITON_SID}}
        DEEPTHT_SID: ${{ secrets.DEEPTHT_SID}}
      run: |
        export BASE_URL=http://twilio.awkwardweirdterribleandbad.com
        export BAKER_URL=$BASE_URL/call/baker
        export FREEBIRD_URL=$BASE_URL/call/freebird
        export GETITON_URL=$BASE_URL/call/getiton
        export DEEPTHT_URL=$BASE_URL/ivr/welcome
        export API_URL="https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/IncomingPhoneNumbers"
        curl -XPOST "${API_URL}/${BAKER_SID}.json" --data-urlencode "VoiceUrl=${BAKER_URL}" -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN"
        curl -XPOST "${API_URL}/${FREEBIRD_SID}.json" --data-urlencode "VoiceUrl=${FREEBIRD_URL}" -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN"
        curl -XPOST "${API_URL}/${GETITON_SID}.json" --data-urlencode "VoiceUrl=${GETITON_URL}" -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN"
        curl -XPOST "${API_URL}/${DEEPTHT_SID}.json" --data-urlencode "VoiceUrl=${DEEPTHT_URL}" -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN"