name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "terraform/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "terraform/**"
  workflow_dispatch:

env:
  CLONE_DIR: ${{ vars.NODEJS_DIR }}/${{ vars.CLONE_DIR }}
  DEPLOY_DIR: ${{ vars.NODEJS_DIR }}/${{ vars.DEPLOY_DIR }}
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.DIGITALOCEAN_HOSTNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_SSH_KEY }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          envs: CLONE_DIR,DEPLOY_DIR,REPO_URL
          script: ../scripts/deploy.sh ${{ vars.CLONE_DIR }} ${{ vars.DEPLOY_DIR }} ${{ vars.REPO_URL }}

      - name: Start NodeJS App
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        env:
          CLONE_DIR: ${{ vars.CLONE_DIR }}
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        with:
          host: ${{ vars.DIGITALOCEAN_HOSTNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_SSH_KEY }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          envs: CLONE_DIR,DEPLOY_DIR,REPO_URL
          script: |
            set -eo pipefail

            echo "::group::Starting App"
            cd "$DEPLOY_DIR"

            echo "::debug::Installing node dependencies"
            sudo -u nodejs npm ci

            echo "::debug::Removing default hello pm2 instance"
            sudo -u nodejs pm2 delete hello || true

            echo "::debug::Starting app and configuring for persistent startup"
            sudo -u nodejs pm2 start ecosystem.config.js --watch
            sudo -u nodejs pm2 save
            echo "::endgroup::"

            echo "::group::Cleanup"
            rm -rf "$CLONE_DIR"
            echo "::endgroup::"

      - name: Update Twilio Webhook URLs
        if: success()
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          HOST: ${{ vars.DIGITALOCEAN_HOSTNAME }}
        run: |
          BASE_URL="http://${HOST}"
          API_URL="https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/IncomingPhoneNumbers"

          post_voice_url() {
            local phone_number="$1"
            local voice_url="$BASE_URL/$2"
            local sid=$(curl -s -XPOST "${API_URL}.json" --data-urlencode "PhoneNumber=$phone_number" -u $TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN | jq -r .sid)
            curl -s -XPOST "${API_URL}/${sid}.json" --data-urlencode "VoiceUrl=${voice_url}" -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN"
          }

          echo "::group::Configuring Twilio Voice URLs"

          post_voice_url "+1269BakerSt" "call/baker"
          post_voice_url "+191Freebird" "call/freebird"
          post_voice_url "+1662GetItOn" "call/getiton"
          post_voice_url "+1660DeepTht" "ivr/welcome"

          echo "::endgroup::"

      - name: Cleanup Deployment
        if: always()
        uses: appleboy/ssh-action@v1.0.0
        env:
          CLONE_DIR: ${{ vars.CLONE_DIR }}
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        with:
          host: ${{ vars.DIGITALOCEAN_HOSTNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_SSH_KEY }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          envs: CLONE_DIR,DEPLOY_DIR,REPO_URL
          script: |
            set -eo pipefail

            echo "::group::Cleanup"
            rm -rf "$CLONE_DIR"
            echo "::endgroup::"
