# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: npm install
    
    - run: npm run build --if-present
    
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Deploy NodeJS App
      uses: appleboy/ssh-action@master
      with:
        host: twilio.awkwardweirdterribleandbad.com
        key: ${{ secrets.DIGITALOCEAN_PRIVATE_SSH_KEY}}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        script: |
          set +e # Do not exit on error
          sudo -u nodejs pm2 delete hello
          set -e # Exit on error
          cd /home/nodejs/
          # Remove any previous clones
          rm -rf /home/nodejs/twilio_apps/
          git clone https://github.com/rodmhgl/twilio_apps.git
          # This is needed for the way I handle precommit hooks
          mkdir -p /home/nodejs/deployed/.git/hooks
          # Copy the updated repo to our deployment folder
          rsync -ac --delete --progress /home/nodejs/twilio_apps/ /home/nodejs/deployed --exclude .git --quiet
          cd /home/nodejs/deployed
          npm install
          sudo -u nodejs pm2 start ecosystem.config.js --watch
          sudo -u nodejs pm2 save
          # Cleanup after ourselves
          rm -rf /home/nodejs/twilio_apps/
          exit