# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - run: npm run build --if-present

      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy NodeJS App
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        env:
          NODEJS_DIR: /home/nodejs
          CLONE_DIR: twilio_apps
          DEPLOY_DIR: deployed
          REPO_URL: "${{ github.server_url}}/${{ github.repository}}.git"
        with:
          host: twilio.awkwardweirdterribleandbad.com
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_SSH_KEY}}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          envs: NODEJS_DIR, CLONE_DIR, DEPLOY_DIR, REPO_URL
          script: |
            set -eo pipefail

            deploy_app() {
              echo "::group::Deploying App"
              echo "::debug::Cleaning up and cloning repo"
              rm -rf "$NODEJS_DIR/$CLONE_DIR"
              git clone "$REPO_URL" "$NODEJS_DIR/$CLONE_DIR"
              echo "::debug::Creating hooks directory"
              mkdir -p "$NODEJS_DIR/$DEPLOY_DIR/.git/hooks"
              echo "::debug::Copying new code to deployment folder"
              rsync -ac --delete --exclude .git "$NODEJS_DIR/$CLONE_DIR/" "$NODEJS_DIR/$DEPLOY_DIR"
              echo "::endgroup::"
            }

            start_app() {
              echo "::group::Starting App"
              cd "$NODEJS_DIR/$DEPLOY_DIR"
              echo "::debug::Installing node dependencies"
              npm install
              echo "::debug::Removing default hello pm2 instance"
              sudo -u nodejs pm2 delete hello || true
              echo "::debug::Starting app and configuring for persistent startup"
              sudo -u nodejs pm2 start ecosystem.config.js --watch
              sudo -u nodejs pm2 save
              echo "::endgroup::"
            }

            cleanup() {
              echo "::group::Cleanup"
              rm -rf "$NODEJS_DIR/$CLONE_DIR"
              echo "::endgroup::"
            }

            deploy_app
            start_app
            cleanup

            exit

      - name: Update Twilio Webhook URLs
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          BAKER_SID: ${{ secrets.BAKER_SID}}
          FREEBIRD_SID: ${{ secrets.FREEBIRD_SID}}
          GETITON_SID: ${{ secrets.GETITON_SID}}
          DEEPTHT_SID: ${{ secrets.DEEPTHT_SID}}
        run: |
          BASE_URL="http://twilio.awkwardweirdterribleandbad.com"
          BAKER_URL="$BASE_URL/call/baker"
          FREEBIRD_URL="$BASE_URL/call/freebird"
          GETITON_URL="$BASE_URL/call/getiton"
          DEEPTHT_URL="$BASE_URL/ivr/welcome"
          API_URL="https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/IncomingPhoneNumbers"

          post_voice_url() {
            local sid="$1"
            local voice_url="$2"
            curl -s -XPOST "${API_URL}/${sid}.json" --data-urlencode "VoiceUrl=${voice_url}" -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN"
          }

          echo "::group::Configuring Twilio Voice URLs"

          post_voice_url "$BAKER_SID" "$BAKER_URL"
          post_voice_url "$FREEBIRD_SID" "$FREEBIRD_URL"
          post_voice_url "$GETITON_SID" "$GETITON_URL"
          post_voice_url "$DEEPTHT_SID" "$DEEPTHT_URL"

          echo "::endgroup::"

          exit
